CREATE TABLE film (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(200) NOT NULL,
                      genre VARCHAR(100) NOT NULL,
                      age_rating INT NOT NULL,
                      director VARCHAR(150) NOT NULL,
                      cast_text VARCHAR(500) NOT NULL,
                      trailer_url VARCHAR(500)
);
