CREATE TABLE hall (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE seat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id BIGINT NOT NULL,
    row_num INT NOT NULL,
    seat_num INT NOT NULL,
    CONSTRAINT fk_seat_hall FOREIGN KEY (hall_id) REFERENCES hall(id),
    CONSTRAINT uq_seat_in_hall UNIQUE (hall_id, row_num, seat_num)
);

CREATE TABLE screening (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    films_id BIGINT NOT NULL,
    hall_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    duration_minutes INT NOT NULL,
    CONSTRAINT fk_screening_film FOREIGN KEY (film_id) REFERENCES film(id),
    CONSTRAINT fk_screening_hall FOREIGN KEY (hall_id) REFERENCES hall(id)
);

CREATE INDEX idx_screening_start_time ON screening(start_time)
CREATE INDEX idx_screening_hall_start ON screening(hall_id, start_time)