CREATE TABLE film_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL,
    CONSTRAINT fk_film_image_film FOREIGN KEY (film_id) REFERENCES film(id)
);

CREATE INDEX idx_film_image_film_id ON film_image(film_id);