CREATE TABLE seat_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screening_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    held_until TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sr_screening FOREIGN KEY (screening_id) REFERENCES screening(id),
    CONSTRAINT fk_sr_seat FOREIGN KEY (seat_id) REFERENCES seat(id),
    CONSTRAINT uq_sr UNIQUE (screening_id, seat_id)
);

CREATE INDEX idx_sr_screening ON seat_reservation(screening_id);
CREATE INDEX idx_sr_status_until ON seat_reservation(status, held_until);