CREATE TABLE booking_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    session_id VARCHAR(100) NOT NULL,
    total_price INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    screening_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    ticket_type VARCHAR(20) NOT NULL,
    price INT NOT NULL,

    CONSTRAINT fk_ticket_order FOREIGN KEY (order_id) REFERENCES booking_order(id),
    CONSTRAINT fk_ticket_screening FOREIGN KEY (screening_id) REFERENCES screening(id),
    CONSTRAINT fk_ticket_seat FOREIGN KEY (seat_id) REFERENCES seat(id),
    CONSTRAINT uq_ticket UNIQUE (screening_id, seat_id)
);